---
title: "consort_diagram"
author: "Daniel Johnson"
date: "2022-08-11"
output:
  pdf_document:
    toc: yes
    toc_depth: '2'
  html_notebook:
    theme: journal
    toc: yes
    toc_depth: 2
    toc_float: yes
---
# Setup

```{r setup, include=FALSE}
library(knitr)
library(tidyverse)
library(lubridate)
library(haven)
library(coxme)
library(survminer)
library(rmdformats)
library(gtsummary)
library(sjPlot)
library(sjlabelled)
library(sjmisc)
library(consort)

knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

# Data sources
```{r data_in}
cand_thor <- read_sas("C:/Users/dyjohnson/Box/SAF 2022 Q2/pubsaf2206/cand_thor.sas7bdat")
JustFormHR <- read_sas("C:/Users/dyjohnson/Box/SAF 2022 Q2/SupplementalData2206/ThoracicRegistration/JustFormHR.sas7bdat")
load("C:/Users/dyjohnson/Box/Heart Data Pipeline/RData files/full_list_pubsaf2206.RData")
```

# CONSORT diagram
```{r consort}
load("C:/Users/dyjohnson/OneDrive/Documents/Research/SRP/full_list_consort.RData")

consort <- full_list %>%
  group_by(PX_ID) %>%
  summarise(
    trialno = PX_ID,
    min_stat = min(as.numeric(as.character(CANHX_STAT_CD))),
    exc1 = case_when(
      min(as.numeric(as.character(CANHX_STAT_CD))) == 2999 ~ "Listed as Inactive",
      !(min(as.numeric(as.character(CANHX_STAT_CD))) %in% c(2110, 2120, 2130, 2140, 2150, 2160, 2999)) ~ "Listed Using Previous Classification
      System", # Change to minimum status
      WL_ORG != "HR" ~ "Listed for Multiple Organs",
      can_listing_ctr_count < 10 ~ "Listed at a Low-volume Center (<10 Heart
      Transplant Candidates Per Year)"
    ),
    arm3 = rec_exception_init_ever,
    .groups = "drop"
  ) %>%
  distinct()

consort_plot <- consort_plot(
  data = consort,
  orders = c(
    trialno = "All Patients < 18 Years Old Listed in 
    SRTR Database from October 18, 2018 
    to December 1, 2021",
    exc1    = "Exclusions",
    trialno = "Study Cohort",
    arm3 = "Exception Status",
    trialno = "Final Analysis"
  ),
  side_box = c("exc1"),
  allocation = "arm3",
  cex = 0.9
)

plot(consort_plot)

ggsave("consort.png", plot = consort_plot)
```

# Patient characteristics
```{r table_1}
load("C:/Users/dyjohnson/OneDrive/Documents/Research/SRP/full_list_clean.RData")
cand_thor <- read_sas("C:/Users/dyjohnson/Box/SAF 2022 Q2/pubsaf2206/cand_thor.sas7bdat")

full_list_px <- full_list %>%
  select(PX_ID, rec_exception_ever, rec_exception_init, exception_start, exception_length, survival_time) %>%
  filter(rec_exception_ever == 0 | !is.na(exception_start)) %>%
  distinct() %>%
  group_by(PX_ID) %>%
  summarise(PX_ID = PX_ID, 
            rec_exception_ever = rec_exception_ever, 
            rec_exception_init = rec_exception_init,
            exception_start = if_else(rec_exception_ever == 1, min(exception_start, na.rm = TRUE), NA_real_),
            exception_percent = sum(exception_length, na.rm = TRUE)/survival_time * 100
            ) %>%
  distinct() %>%
  left_join(cand_thor, by = "PX_ID") %>%
  ungroup()

fortable1 <- full_list_px %>%
  mutate(
    age = CAN_AGE_AT_LISTING,
    agegroup = factor(
      case_when(
        age >= 18 & age < 35 ~ "18-34",
        age >= 35 & age < 55 ~ "35-54",
        age >= 55 & age < 65 ~ "55-64",
        age >= 65 & age < 75 ~ "65-74",
        age >= 75 ~ ">75"
      ),
      levels = c("18-34",
                 "35-54",
                 "55-64",
                 "65-74",
                 ">75")
    ),
    sex = factor(
      case_when(CAN_GENDER == "M" ~ "Male",
                TRUE ~ "Female"),
      levels = c("Male", "Female")
    ),
    race = factor(
      case_when(
        CAN_RACE == 8 ~ "White",
        CAN_RACE == 16 ~ "Black",
        CAN_RACE == 2000 ~ "Hispanic",
        CAN_RACE == 64 ~ "Asian",
        TRUE ~ "Other"
      ),
      levels = c("White",
                 "Black",
                 "Hispanic",
                 "Asian",
                 "Other")
    ),
    functional_status = factor(
      case_when(
        CAN_FUNCTN_STAT > 2079 ~ "Little to no impairment, 80-100%",
        CAN_FUNCTN_STAT > 2049 &
          CAN_FUNCTN_STAT < 4071 ~ "Moderate impairment, 50-70%",
        CAN_FUNCTN_STAT > 2009 &
          CAN_FUNCTN_STAT < 4041 ~ "Severe impairment, 10-40%",
        TRUE ~ "Unknown"
      )
    ),
    blood_type = factor(
      case_when(
        CAN_ABO %in% c("A", "A1", "A2") ~ "A",
        CAN_ABO %in% c("A1B", "A2B") ~ "AB",
        TRUE ~ CAN_ABO
      )
    ),
    payor = factor(
      case_when(
        CAN_PRIMARY_PAY %in% c(2, 3, 4, 5, 6, 7, 13) ~ "Public",
        CAN_PRIMARY_PAY == 1 ~ "Private",
        TRUE ~ "Other"
      ),
      levels = c("Private",
                 "Public",
                 "Other")
    ),
    primary_diagnosis = factor(
      case_when(
        CAN_DGN %in% c(
          1000,
          1001,
          1002,
          1003,
          1004,
          1005,
          1006,
          1049,
          1050,
          1051,
          1052,
          1053,
          1054,
          1099,
          1201
        ) ~ "Nonischemic cardiomyopathy",
        CAN_DGN == 1007 ~ "Ischemic cardiomyopathy",
        TRUE ~ "Other"
      )
    ),
    rec_exception_init_ever = factor(
      case_when(
        rec_exception_init == 1 ~ "Initial exception",
        rec_exception_ever == 1 ~ "Later exception",
        TRUE ~ "No exception"
      )
    ),
    rec_exception_ever = factor(
      case_when(
        rec_exception_ever == 1 ~ "Status exception",
        TRUE ~ "No status exception"
      ),
      levels = c("Status exception",
                 "No status exception")
    ),
    rec_exception_init = factor(
      case_when(
        rec_exception_init == 1 ~ "Initial status exception",
        TRUE ~ "No initial status exception"
      ),
      levels = c("Initial status exception",
                 "No initial status exception")
    ),
    diabetes = factor(
      case_when(
        CAN_DIAB_TY %in% c(2, 3, 4, 5) ~ "Diabetes",
        CAN_DIAB_TY == 1 ~ "No diabetes",
        TRUE ~ "Unknown"
      )
    ),
    cva = factor(
      case_when(
        CAN_CEREB_VASC == "Y" ~ "CVA",
        CAN_CEREB_VASC == "N" ~ "No CVA",
        TRUE ~ "Unknown"
      )
    ),
    smoking = factor(
      case_when(CAN_HIST_CIGARETTE == "Y" ~ "Smoking",
                TRUE ~ "No smoking"),
      levels = c("Smoking",
                 "No smoking")
    ),
    aicd = factor(
      case_when(
        CAN_IMPLANT_DEFIB == "Y" ~ "AICD",
        CAN_IMPLANT_DEFIB == "N" ~ "No AICD",
        TRUE ~ "Unknown"
      )
    ),
    init_status = factor(
      case_when(
        CAN_INIT_STAT == 2110 ~ "Status 1",
        CAN_INIT_STAT == 2120 ~ "Status 2",
        CAN_INIT_STAT == 2130 ~ "Status 3",
        CAN_INIT_STAT == 2140 ~ "Status 4",
        CAN_INIT_STAT == 2150 ~ "Status 5",
        CAN_INIT_STAT == 2160 ~ "Status 6",
        CAN_INIT_STAT == 2999 ~ "Temporarily inactive"
      )
    ),
    bsa = 0.007184 * (CAN_HGT_CM ^ 0.725) * (CAN_WGT_KG ^ 0.425),
    cardiac_index = CAN_CARDIAC_OUTPUT / bsa,
    CAN_IV_INOTROP = factor(
      case_when(
        CAN_IV_INOTROP == 0 ~ "No",
        CAN_IV_INOTROP == 1 ~ "Yes",
        TRUE ~ "Unknown"
      )
    ),
    CAN_IABP = factor(
      case_when(CAN_IABP == 0 ~ "No",
                CAN_IABP == 1 ~ "Yes",
                TRUE ~ "Unknown")
    ),
    CAN_ECMO = factor(
      case_when(CAN_ECMO == 0 ~ "No",
                CAN_ECMO == 1 ~ "Yes",
                TRUE ~ "Unknown")
    ),
    mcsd = factor(
      case_when(
        CAN_VAD_TY == 1 ~ "None",
        CAN_VAD_TY == 2 ~ "LVAD",
        CAN_VAD_TY == 3 ~ "RVAD",
        CAN_VAD_TY == 4 ~ "TAH",
        CAN_VAD_TY == 5 ~ "BiVAD",
        TRUE ~ "Unknown"
      ),
      levels = c("None",
                 "LVAD",
                 "RVAD",
                 "TAH",
                 "BiVAD",
                 "Unknown")
    ),
    lvad = factor(
      case_when(
        CAN_VAD_TY == 2 ~ "Durable LVAD",
        TRUE ~ "No durable LVAD"
      ),
      levels = c("Durable LVAD",
                 "No durable LVAD")
    ),
    other_mcs = factor(
      case_when(
        CAN_VAD_TY %in% c(3, 4, 5) ~ "Other MCS",
        TRUE ~ "No other MCS"
      ),
      levels = c("Other MCS",
                 "No other MCS")
    ),
    no_mcs = factor(
      case_when(
        !(CAN_VAD_TY %in% c(2, 3, 4, 5)) ~ "No MCS",
        TRUE ~ "MCS"
      ),
      levels = c("No MCS",
                 "MCS")
    ),
    dialysis = factor(
      case_when(
        CAN_DIAL == 1 ~ "No dialysis",
        CAN_DIAL %in% c(2, 3, 4, 5) ~ "Dialysis",
        TRUE ~ "Unknown"
      ),
      levels = c("No dialysis",
                 "Dialysis",
                 "Unknown")
    )
  ) 

var_label_list <- list(age = "Age at listing (years)",
                       agegroup = "Age group",
                       sex = "Sex",
                       race = "Race",
                       blood_type = "Blood type",
                       CAN_BMI = "BMI, kg/m^2",
                       bsa = "BSA",
                       functional_status= "Functional status at listing",
                       payor = "Insurance type",
                       primary_diagnosis = "Primary diagnosis",
                       rec_exception_init_ever = "Receipt of exception",
                       rec_exception_ever = "Receipt of exception",
                       rec_exception_init = "Receipt of initial exception",
                       exception_start = "Time to initial exception",
                       exception_percent = "Percentage of waitlist time spent in exception status",
                       diabetes = "Diabetes",
                       cva = "CVA",
                       smoking = "Smoking",
                       aicd = "AICD",
                       init_status = "Status at listing",
                       CAN_PULM_ART_SYST = "PA systolic, mm Hg",
                       CAN_PULM_ART_DIAST = "PA diastolic, mm Hg",
                       CAN_PCW_MEAN = "PCWP, mm Hg",
                       cardiac_index = "Cardicac index, L/min per m^2",
                       CAN_IV_INOTROP = "Inotrope at listing",
                       CAN_IABP = "IABP at listing",
                       CAN_ECMO = "ECMO at listing",
                       mcsd = "MCSD at listing",
                       lvad = "Durable LVAD",
                       other_mcs = "Other MCS",
                       no_mcs = "No MCS",
                       CAN_MOST_RECENT_CREAT = "Serum creatinine",
                       dialysis = "Dialysis"
                       )

labelled::var_label(fortable1) <- var_label_list

fortable1 %>%
  select(
    # rec_exception_ever,
    # rec_exception_init,
    rec_exception_init_ever,
    age,
    sex,
    race,
    payor,
    CAN_BMI,
    init_status,
    functional_status,
    primary_diagnosis,
    diabetes,
    cva,
    CAN_IABP,
    CAN_ECMO,
    lvad,
    other_mcs,
    no_mcs,
    exception_start,
    exception_percent
  ) %>%
  tbl_summary(by = rec_exception_init_ever,
              missing = "no",
              label = list(sex ~ "Female"),
              value = list(sex ~ "Female",
                           diabetes ~ "Diabetes",
                           cva ~ "CVA",
                           lvad ~ "Durable LVAD",
                           other_mcs ~ "Other MCS",
                           no_mcs ~ "No MCS")) %>%
  add_p(test.args = all_tests("fisher.test") ~ list(workspace=2e7)) %>%
  add_overall() %>%
  as_gt() %>%
  gt::gtsave(
    filename = "table1.png"
  )

fortable1 %>%
  select(
    rec_exception_init,
    age,
    sex,
    race,
    payor,
    CAN_BMI,
    init_status
  ) %>%
  tbl_summary(by = rec_exception_init,
              missing = "no",
              label = list(sex ~ "Female"),
              value = list(sex ~ "Female")
              ) %>%
  add_p(test.args = all_tests("fisher.test") ~ list(workspace=2e7)) %>%
  add_overall() %>%
  as_gt() %>%
  gt::gtsave(
  filename = "table1_short1.png"
  )

fortable1 %>%
  select(
    rec_exception_init,
    functional_status,
    primary_diagnosis,
    diabetes,
    cva,
    CAN_IABP,
    CAN_ECMO,
    lvad,
    other_mcs,
    no_mcs
  ) %>%
  tbl_summary(by = rec_exception_init,
              missing = "no",
              value = list(diabetes ~ "Diabetes",
                           cva ~ "CVA",
                           lvad ~ "Durable LVAD",
                           other_mcs ~ "Other MCS",
                           no_mcs ~ "No MCS")
              ) %>%
  add_p(test.args = all_tests("fisher.test") ~ list(workspace=2e7)) %>%
  add_overall() %>%
  as_gt() %>%
  gt::gtsave(
    filename = "table1_short2.png"
  )
```

# Descriptive plots

```{r descriptive_plots}
# Bar chart of exceptions by status

## Create status_approved2, which is the same as status_approved but doesn't fill forward
full_list <- full_list %>%
  mutate(status_approved2 = case_when(
    Exception == 1 &
      ApplicationStatus %in% c(8, 10, 12, 13, 14, 16, 19, 27) &
      RequestedCandStatCd == 2110 ~ "Status 1",
    Exception == 1 &
      ApplicationStatus %in% c(8, 10, 12, 13, 14, 16, 19, 27) &
      RequestedCandStatCd == 2120 ~ "Status 2",
    Exception == 1 &
      ApplicationStatus %in% c(8, 10, 12, 13, 14, 16, 19, 27) &
      RequestedCandStatCd == 2130 ~ "Status 3",
    Exception == 1 &
      ApplicationStatus %in% c(8, 10, 12, 13, 14, 16, 19, 27) &
      RequestedCandStatCd == 2140 ~ "Status 4",
    Exception == 1 &
      ApplicationStatus %in% c(8, 10, 12, 13, 14, 16, 19, 27) &
      RequestedCandStatCd == 2150 ~ "Status 5",
    Exception == 1 &
      ApplicationStatus %in% c(8, 10, 12, 13, 14, 16, 19, 27) &
      RequestedCandStatCd == 2160 ~ "Status 6",
    ),
    status_approved2 = factor(status_approved2, levels = c(
          "Status 1",
          "Status 2",
          "Status 3",
          "Status 4",
          "Status 5",
          "Status 6"))
  )

d <- full_list %>%
  filter(
    !is.na(status_approved2) &
      status_approved2 %in% c("Status 1", "Status 2", "Status 3", "Status 4")
  )

ggplot(d, aes(status_approved2)) + 
  geom_bar() +
  labs(x = "Status Exception Approved", y = "Count")

ggsave("status_approved.png", width = 5, height = 5)

status_approved_prop <- full_list %>%
  filter(can_stat_active %in% c(2110, 2120, 2130, 2140)) %>%
  select(PX_ID,
         t_start,
         t_stop,
         can_stat_active,
         rec_exception) %>%
  mutate(
    can_stat_active = case_when(
      can_stat_active == 2110 ~ "Status 1",
      can_stat_active == 2120 ~ "Status 2",
      can_stat_active == 2130 ~ "Status 3",
      can_stat_active == 2140 ~ "Status 4",
    )
  ) %>%
  group_by(can_stat_active) %>%
  summarise(proportion_ex = mean(rec_exception) * 100) %>%
  ungroup()

ggplot(status_approved_prop, aes(can_stat_active, proportion_ex)) + 
  geom_col() +
  labs(x = "Status Exception Approved", y = "Proportion of Candidates with Exceptions")

ggsave("status_approved_prop.png", width = 5, height = 5)

# Stacked bar chart
## Select only rows with changes in status or exception status
for_stack <- full_list %>%
  group_by(PX_ID) %>%
  mutate(
    rec_exception_status = factor(
      case_when(
        can_stat_active == 2110 &
          rec_exception == 0 ~ "Status 1 no exception",
        can_stat_active == 2110 &
          rec_exception == 1 ~ "Status 1 exception",
        can_stat_active == 2120 &
          rec_exception == 0 ~ "Status 2 no exception",
        can_stat_active == 2120 &
          rec_exception == 1 ~ "Status 2 exception",
        can_stat_active == 2130 &
          rec_exception == 0 ~ "Status 3 no exception",
        can_stat_active == 2130 &
          rec_exception == 1 ~ "Status 3 exception",
        can_stat_active == 2140 &
          rec_exception == 0 ~ "Status 4 no exception",
        can_stat_active == 2140 &
          rec_exception == 1 ~ "Status 4 exception",
        can_stat_active == 2150 ~ "Status 5",
        can_stat_active == 2160 ~ "Status 6"
      )
    ),
    rec_exception_status_prev = lag(rec_exception_status),
    rec_exception_status_change = case_when(rec_exception_status != rec_exception_status_prev | is.na(rec_exception_status_prev) ~ 1,
                                            TRUE ~ 0),
    can_stat_active = factor(
      case_when(
        can_stat_active == 2110 ~ "Status 1",
        can_stat_active == 2120 ~ "Status 2",
        can_stat_active == 2130 ~ "Status 3",
        can_stat_active == 2140 ~ "Status 4",
        can_stat_active == 2150 ~ "Status 5",
        can_stat_active == 2160 ~ "Status 6"
      ),
      levels = c(
        "Status 1",
        "Status 2",
        "Status 3",
        "Status 4",
        "Status 5",
        "Status 6"
      )
    ),
    rec_exception = factor(
      case_when(
        rec_exception == 1 ~ "Exception",
        TRUE ~ "No exception"), 
      levels = c("Exception", "No exception"))
  ) %>%
  filter(rec_exception_status_change == 1) %>%
  select(-c(rec_exception_status_prev, rec_exception_status_change))
  
for_stack %>% select(PX_ID, unique_date_start, can_stat_active, rec_exception, rec_exception_status) %>% View()

ggplot(for_stack, aes(x = can_stat_active, fill = rec_exception)) + 
  geom_bar() + 
  labs(x = "Status", y = "Number of Candidates", fill = "")

ggsave("status_stack.png", width = 10, height = 5)

# Chart of exceptions by time of exception
ggplot(d, aes(status_approved2, t_start)) +
  geom_boxplot(outlier.shape = NA) +
  coord_cartesian(ylim = quantile(d$t_start, c(0.1, 0.9))) +
  labs(x = "Status Exception Approved", y = "Day Exception Approved")

ggsave("exception_by_time.png", width = 5, height = 5)

# Bar chart of exceptions by duration of exceptions
e <- full_list %>%
  filter(
    rec_exception == 1
  ) %>%
  select(PX_ID, exception_start, exception_stop, exception_length) %>%
  mutate(exception_length_mo = exception_length/30.437) %>%
  unique()

ggplot(e, aes(exception_length_mo)) +
  geom_histogram(binwidth = 1) +
  labs(x = "Status Exception Length (months)", y = "Count")

ggsave("exception_by_length.png")
```

# Patient funnel plot

```{r funnel_plot}
load("C:/Users/dyjohnson/OneDrive/Documents/Research/SRP/full_list_for_funnel.RData")
cand_thor <- read_sas("C:/Users/dyjohnson/Box/SAF 2022 Q2/pubsaf2206/cand_thor.sas7bdat")

# Graph proportions of exceptions over time
full_list_for_funnel <- full_list_for_funnel %>%
  filter(
    CAN_AGE_IN_MONTHS_AT_LISTING >= 216 &
      CAN_LISTING_DT >= as.Date("2018-10-18") &
      CAN_LISTING_DT <= as.Date("2021-12-01") &
      min(as.numeric(as.character(CANHX_STAT_CD))) != 2999 &
      CAN_INIT_STAT %in% c(2110, 2120, 2130, 2140, 2150, 2160, 2999) &
      WL_ORG == "HR" &
      can_listing_ctr_count >= 10
  )

full_list_for_funnel <- left_join(full_list_for_funnel, cand_thor %>% select(PX_ID, CAN_SOURCE), by = "PX_ID")

full_list_for_funnel <- full_list_for_funnel %>%
  group_by(PX_ID) %>%
  mutate(big_stat = factor(
    case_when(
      death == 1 & rec_exception == 1 ~ "dead_w_exception",
      death == 1 & rec_exception == 0 ~ "dead_wo_exception",
      unique_date >= REC_TX_DT &
        rec_exception == 1 ~ "transplant_w_exception",
      unique_date >= REC_TX_DT &
        rec_exception == 0 ~ "transplant_wo_exception", 
      t_start == max(t_start) &
        CAN_SOURCE == "R" &
        death == 0 &
        rec_exception == 1 ~ "delisted_w_exception",
      t_start == max(t_start) &
        CAN_SOURCE == "R" &
        death == 0 &
        rec_exception == 0 ~ "delisted_wo_exception",
      rec_exception == 1 ~ "alive_w_exception",
      rec_exception == 0 ~ "alive_wo_exception"
    )
  ),
  big_stat2 = factor(
    case_when(
      death == 1 & rec_exception == 1 ~ "dead_w_exception",
      death == 1 & rec_exception == 0 ~ "dead_wo_exception",
      unique_date >= REC_TX_DT &
        rec_exception == 1 ~ "transplant_w_exception",
      unique_date >= REC_TX_DT &
        rec_exception == 0 ~ "transplant_wo_exception", 
      t_start == max(t_start) &
        CAN_SOURCE == "R" &
        death == 0 &
        rec_exception == 1 ~ "delisted_w_exception",
      t_start == max(t_start) &
        CAN_SOURCE == "R" &
        death == 0 &
        rec_exception == 0 ~ "delisted_wo_exception",
      can_stat_active == 2110 &
        rec_exception == 1 ~ "stat_1_w_exception",
      can_stat_active == 2110 &
        rec_exception == 0 ~ "stat_1_wo_exception",
      can_stat_active == 2120 &
        rec_exception == 1 ~ "stat_2_w_exception",
      can_stat_active == 2120 &
        rec_exception == 0 ~ "stat_2_wo_exception",
      can_stat_active == 2130 &
        rec_exception == 1 ~ "stat_3_w_exception",
      can_stat_active == 2130 &
        rec_exception == 0 ~ "stat_3_wo_exception",
      can_stat_active == 2140 &
        rec_exception == 1 ~ "stat_4_w_exception",
      can_stat_active == 2140 &
        rec_exception == 0 ~ "stat_4_wo_exception",
      can_stat_active == 2150 ~ "stat_5",
      can_stat_active == 2160 ~ "stat_6"
    )
  )) %>%
  ungroup()

full_list_for_funnel <- full_list_for_funnel %>%
  select(PX_ID, t_start) %>%
  group_by(PX_ID) %>%
  summarise(t_start = seq(0, 100),
            .groups = "drop") %>%
  full_join(full_list_for_funnel %>% 
              select(PX_ID, t_start, can_stat_active, rec_exception, big_stat, big_stat2),
            by = c("PX_ID", "t_start"))  %>%
  fill(everything(), .direction = "down") %>%
  ungroup() %>%
  filter(t_start <= 100)

alive <- full_list_for_funnel %>%
  group_by(t_start) %>%
  count(big_stat) %>% 
  ungroup() %>% 
  spread(key = big_stat, value = n) %>% 
  mutate_all(funs(replace(., is.na(.), 0))) %>% 
  rename(time = t_start)
  
# Check sums
# alive %>% mutate(sum = alive_w_exception + alive_wo_exception + delisted_w_exception + delisted_wo_exception + dead_w_exception + dead_wo_exception + transplant_w_exception + transplant_wo_exception) %>% View()

status <- full_list_for_funnel %>%
  group_by(t_start) %>%
  count(big_stat2) %>% 
  ungroup() %>% 
  spread(key = big_stat2, value = n) %>% 
  mutate_all(funs(replace(., is.na(.), 0))) %>% 
  rename(time = t_start)

# Check sums
# status %>% mutate(sum = stat_1_w_exception + stat_1_wo_exception + stat_2_w_exception + stat_2_wo_exception + stat_3_w_exception + stat_3_wo_exception + stat_4_w_exception +stat_4_wo_exception + stat_5 + stat_6 + delisted_w_exception + delisted_wo_exception + dead_w_exception + dead_wo_exception + transplant_w_exception + transplant_wo_exception) %>% View()

cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7", "#000000")

RColorBrewer::brewer.pal(12, "Paired")

population_time <- ggplot(data = alive, aes(x = time)) +
  geom_area(
    aes(y = alive_w_exception, fill = "Alive with exception"),
    colour = "black",
    alpha = 0.75
  ) +
  geom_ribbon(
    aes(
      ymax = alive_w_exception + alive_wo_exception,
      ymin = alive_w_exception,
      fill = "Alive without exception"
    ),
    colour = "black",
    alpha = 0.75
  ) +
  geom_ribbon(
    aes(
      ymax = alive_w_exception + alive_wo_exception + transplant_w_exception,
      ymin = alive_w_exception + alive_wo_exception,
      fill = "Transplanted with exception"
    ),
    colour = "black",
    alpha = 0.75
  ) +
  geom_ribbon(
    aes(
      ymax = alive_w_exception + alive_wo_exception + transplant_w_exception + transplant_wo_exception,
      ymin = alive_w_exception + alive_wo_exception + transplant_w_exception,
      fill = "Transplanted without exception"
    ),
    colour = "black",
    alpha = 0.75
  ) +
  geom_ribbon(
    aes(
      ymax = alive_w_exception + alive_wo_exception + transplant_w_exception + transplant_wo_exception + delisted_w_exception,
      ymin = alive_w_exception + alive_wo_exception + transplant_w_exception + transplant_wo_exception,
      fill = "Delisted with exception"
    ),
    colour = "black",
    alpha = 0.75
  ) +
  geom_ribbon(
    aes(
      ymax = alive_w_exception + alive_wo_exception + transplant_w_exception + transplant_wo_exception + delisted_w_exception + delisted_wo_exception,
      ymin = alive_w_exception + alive_wo_exception + transplant_w_exception + transplant_wo_exception + delisted_w_exception,
      fill = "Delisted without exception"
    ),
    colour = "black",
    alpha = 0.75
  ) +
  labs(y = "Number of Patients Alive", x = "Days Since Listing") +
  scale_fill_manual(values = cbPalette,
                    name = "",
                    breaks = c("Alive with exception", "Alive without exception", "Transplanted with exception", "Transplanted without exception", "Delisted with exception", "Delisted without exception"),
                    labels = c("Alive with exception", "Alive without exception", "Transplanted with exception", "Transplanted without exception", "Delisted with exception", "Delisted without exception")) +
  theme_minimal() + scale_x_continuous(breaks = seq(0, 100, 20)) + scale_y_continuous(breaks = seq(0, 13000, 1000))

population_time

ggsave("population_time.png")

stat_time <- ggplot(data = status, aes(x = time)) +
  geom_area(
    aes(y = stat_1_w_exception, fill = "Status 1 with exception"),
    colour = "black",
    alpha = 0.75
  ) +
  geom_ribbon(
    aes(
      ymax = stat_1_w_exception + stat_1_wo_exception,
      ymin = stat_1_w_exception,
      fill = "Status 1 without exception"
    ),
    colour = "black",
    alpha = 0.75
  ) +
  geom_ribbon(
    aes(
      ymax = stat_1_w_exception + stat_1_wo_exception + stat_2_w_exception,
      ymin = stat_1_w_exception + stat_1_wo_exception,
      fill = "Status 2 with exception"
    ),
    colour = "black",
    alpha = 0.75
  ) +
  geom_ribbon(
    aes(
      ymax = stat_1_w_exception + stat_1_wo_exception + stat_2_w_exception + stat_2_wo_exception,
      ymin = stat_1_w_exception + stat_1_wo_exception + stat_2_w_exception,
      fill = "Status 2 without exception"
    ),
    colour = "black",
    alpha = 0.75
  ) +
  geom_ribbon(
    aes(
      ymax = stat_1_w_exception + stat_1_wo_exception + stat_2_w_exception + stat_2_wo_exception + stat_3_w_exception,
      ymin = stat_1_w_exception + stat_1_wo_exception + stat_2_w_exception + stat_2_wo_exception,
      fill = "Status 3 with exception"
    ),
    colour = "black",
    alpha = 0.75
  ) +
  geom_ribbon(
    aes(
      ymax = stat_1_w_exception + stat_1_wo_exception + stat_2_w_exception + stat_2_wo_exception + stat_3_w_exception + stat_3_wo_exception,
      ymin = stat_1_w_exception + stat_1_wo_exception + stat_2_w_exception + stat_2_wo_exception + stat_3_w_exception,
      fill = "Status 3 without exception"
    ),
    colour = "black",
    alpha = 0.75
  ) +
  geom_ribbon(
    aes(
      ymax = stat_1_w_exception + stat_1_wo_exception + stat_2_w_exception + stat_2_wo_exception + stat_3_w_exception + stat_3_wo_exception + stat_4_w_exception,
      ymin = stat_1_w_exception + stat_1_wo_exception + stat_2_w_exception + stat_2_wo_exception + stat_3_w_exception + stat_3_wo_exception,
      fill = "Status 4 with exception"
    ),
    colour = "black",
    alpha = 0.75
  ) +
  geom_ribbon(
    aes(
      ymax = stat_1_w_exception + stat_1_wo_exception + stat_2_w_exception + stat_2_wo_exception + stat_3_w_exception + stat_3_wo_exception + stat_4_w_exception + stat_4_wo_exception,
      ymin = stat_1_w_exception + stat_1_wo_exception + stat_2_w_exception + stat_2_wo_exception + stat_3_w_exception + stat_3_wo_exception + stat_4_w_exception,
      fill = "Status 4 without exception"
    ),
    colour = "black",
    alpha = 0.75
  ) +
  geom_ribbon(
    aes(
      ymax = stat_1_w_exception + stat_1_wo_exception + stat_2_w_exception + stat_2_wo_exception + stat_3_w_exception + stat_3_wo_exception + stat_4_w_exception + stat_4_wo_exception + stat_5,
      ymin = stat_1_w_exception + stat_1_wo_exception + stat_2_w_exception + stat_2_wo_exception + stat_3_w_exception + stat_3_wo_exception + stat_4_w_exception + stat_4_wo_exception,
      fill = "Status 5"
    ),
    colour = "black",
    alpha = 0.75
  ) +
  geom_ribbon(
    aes(
      ymax = stat_1_w_exception + stat_1_wo_exception + stat_2_w_exception + stat_2_wo_exception + stat_3_w_exception + stat_3_wo_exception + stat_4_w_exception + stat_4_wo_exception + stat_5 + stat_6,
      ymin = stat_1_w_exception + stat_1_wo_exception + stat_2_w_exception + stat_2_wo_exception + stat_3_w_exception + stat_3_wo_exception + stat_4_w_exception + stat_4_wo_exception + stat_5,
      fill = "Status 6"
    ),
    colour = "black",
    alpha = 0.75
  ) +
  geom_ribbon(
    aes(
      ymax = stat_1_w_exception + stat_1_wo_exception + stat_2_w_exception + stat_2_wo_exception + stat_3_w_exception + stat_3_wo_exception + stat_4_w_exception + stat_4_wo_exception + stat_5 + stat_6 + transplant_w_exception + transplant_wo_exception,
      ymin = stat_1_w_exception + stat_1_wo_exception + stat_2_w_exception + stat_2_wo_exception + stat_3_w_exception + stat_3_wo_exception + stat_4_w_exception + stat_4_wo_exception + stat_5 + stat_6,
      fill = "Transplanted"
    ),
    colour = "black",
    alpha = 0.75
  ) +
  geom_ribbon(
    aes(
      ymax = stat_1_w_exception + stat_1_wo_exception + stat_2_w_exception + stat_2_wo_exception + stat_3_w_exception + stat_3_wo_exception + stat_4_w_exception + stat_4_wo_exception + stat_5 + stat_6 + transplant_w_exception + transplant_wo_exception + delisted_w_exception + delisted_wo_exception,
      ymin = stat_1_w_exception + stat_1_wo_exception + stat_2_w_exception + stat_2_wo_exception + stat_3_w_exception + stat_3_wo_exception + stat_4_w_exception + stat_4_wo_exception + stat_5 + stat_6 + transplant_w_exception + transplant_wo_exception,
      fill = "Delisted"
    ),
    colour = "black",
    alpha = 0.75
  ) +
  labs(y = "Number of Patients Alive", x = "Days Since Listing") +
  scale_fill_manual(
    name = "",
    values = c(
      "Status 1 with exception" = "#A6CEE3",
      "Status 1 without exception" = "#1F78B4",
      "Status 2 with exception" = "#B2DF8A",
      "Status 2 without exception" = "#33A02C",
      "Status 3 with exception" = "#FB9A99",
      "Status 3 without exception" = "#E31A1C",
      "Status 4 with exception" = "#FDBF6F",
      "Status 4 without exception" = "#FF7F00",
      "Status 5" = "#CAB2D6",
      "Status 6" = "#6A3D9A",
      "Transplanted" = "#FFFF99",
      "Delisted" = "#B15928"
    )
  ) +
  theme_minimal() + scale_x_continuous(breaks = seq(0, 100, 20)) + scale_y_continuous(breaks = seq(0, 13000, 1000))

temp <- c(
      "Status 1 with exception" = "#A6CEE3",
      "Status 1 without exception" = "#1F78B4",
      "Status 2 with exception" = "#B2DF8A",
      "Status 2 without exception" = "#33A02C",
      "Status 3 with exception" = "#FB9A99",
      "Status 3 without exception" = "#E31A1C",
      "Status 4 with exception" = "#FDBF6F",
      "Status 4 without exception" = "#FF7F00",
      "Status 5" = "#CAB2D6",
      "Status 6" = "#6A3D9A",
      "Transplanted" = "#FFFF99",
      "Delisted" = "#B15928"
    )

stat_time

ggsave("stat_time.png")
```

# Sankey plot
```{r sankey}
library(ggsankey)

data(mtcars)

df <- mtcars %>%
  make_long(cyl, vs, am, gear, carb)

# for_sankey <- full_list %>%
#   make_long(can_stat_active)

ggplot(df, aes(x = x, 
               next_x = next_x, 
               node = node, 
               next_node = next_node,
               fill = factor(node),
               label = node)) +
  geom_sankey() +
  geom_sankey_label() +
  theme_sankey(base_size = 16)
```

# Cox model

Test Cox models with different specifications
```{r cox_models}
load("C:/Users/dyjohnson/OneDrive/Documents/Research/SRP/full_list_clean.RData")

full_list_cox <- full_list %>%
    select(
    PX_ID,
    t_start,
    t_stop,
    unique_date_start,
    death,
    final_removal_dt,
    CANHX_STAT_CD,
    can_stat_active,
    rec_exception,
    CAN_LISTING_CTR_ID
  ) %>%
  filter(
    unique_date_start <= final_removal_dt
  ) %>%
  mutate(
    can_stat_active = factor(
      case_when(
        can_stat_active == 2110 ~ "Status 1",
        can_stat_active == 2120 ~ "Status 2",
        can_stat_active == 2130 ~ "Status 3",
        can_stat_active == 2140 ~ "Status 4",
        can_stat_active == 2150 ~ "Status 5",
        can_stat_active == 2160 ~ "Status 6"
      )
    ),
    can_stat_active = relevel(can_stat_active, ref = "Status 6"),
    rec_exception_status = factor(
      case_when(
        can_stat_active == "Status 1" & rec_exception == 0 ~ "Status 1 no exception",
        can_stat_active == "Status 1" & rec_exception == 1 ~ "Status 1 exception",
        can_stat_active == "Status 2" & rec_exception == 0 ~ "Status 2 no exception",
        can_stat_active == "Status 2" & rec_exception == 1 ~ "Status 2 exception",
        can_stat_active == "Status 3" & rec_exception == 0 ~ "Status 3 no exception",
        can_stat_active == "Status 3" & rec_exception == 1 ~ "Status 3 exception",
        can_stat_active == "Status 4" & rec_exception == 0 ~ "Status 4 no exception",
        can_stat_active == "Status 4" & rec_exception == 1 ~ "Status 4 exception",
        can_stat_active == "Status 5" ~ "Status 5",
        TRUE ~ "Status 6"),
      levels = c(
        "Status 1 no exception",
        "Status 1 exception",
        "Status 2 no exception",
        "Status 2 exception",
        "Status 3 no exception",
        "Status 3 exception",
        "Status 4 no exception",
        "Status 4 exception",
        "Status 5",
        "Status 6"
      )
    ),
    rec_exception_status = relevel(rec_exception_status, ref = "Status 6")
)


# All statuses and exceptions
coxph_stat_ex_long <- coxph(Surv(t_start, t_stop, death) ~ rec_exception_status, data = full_list_cox)

summary(coxph_stat_ex_long)

plot_model(
  coxph_stat_ex_long,
  show.values = TRUE,
  value.offset = .3,
  axis.labels = c(
    "Status 5",
    "Status 4 exception",
    "Status 4 no exception",
    "Status 3 exception",
    "Status 3 no exception",
    "Status 2 exception",
    "Status 2 no exception",
    "Status 1 exception",
    "Status 1 no exception"
  ),
  title = "Proportional Hazards Model",
  axis.title = "Hazard Ratio"
)

ggsave("coxph_stat_ex_long.png")

# All statuses and exceptions and random center effects
coxme_stat_ex_long <- coxme(Surv(t_start, t_stop, death) ~ rec_exception_status + (1 | CAN_LISTING_CTR_ID), data = full_list_cox)

summary(coxme_stat_ex_long)

plot_model(
  coxme_stat_ex_long,
  show.values = TRUE,
  value.offset = .3,
  axis.labels = c(
    "Status 5",
    "Status 4 exception",
    "Status 4 no exception",
    "Status 3 exception",
    "Status 3 no exception",
    "Status 2 exception",
    "Status 2 no exception",
    "Status 1 exception",
    "Status 1 no exception"
  ),
  title = "Mixed Effects Model with Center Random Effects",
  axis.title = "Hazard Ratio"
)

ggsave("coxme_stat_ex_long.png")

# All statuses and exceptions and random effects for center and exception
coxme_stat_ex_long_exrand <- coxme(Surv(t_start, t_stop, death) ~ rec_exception_status + (1 + rec_exception | CAN_LISTING_CTR_ID), data = full_list_cox)

summary(coxme_stat_ex_long_exrand)

plot_model(
  coxme_stat_ex_long_exrand,
  show.values = TRUE,
  value.offset = .3,
  axis.labels = c(
    "Status 5",
    "Status 4 exception",
    "Status 4 no exception",
    "Status 3 exception",
    "Status 3 no exception",
    "Status 2 exception",
    "Status 2 no exception",
    "Status 1 exception",
    "Status 1 no exception"
  ),
  title = "Mixed Effects Model with Center and Exception Random Effects",
  axis.title = "Hazard Ratio"
)

ggsave("coxme_stat_ex_long_exrand.png")

# Table of hazard ratios
hrs <- data.frame(
  Status = c("Status 1", "Status 2", "Status 3", "Status 4"),
  Proportional_Hazards = c(
    exp(coef(coxph_stat_ex_long)[1] + coef(coxph_stat_ex_long)[2]),
    exp(coef(coxph_stat_ex_long)[3] + coef(coxph_stat_ex_long)[4]),
    exp(coef(coxph_stat_ex_long)[5] + coef(coxph_stat_ex_long)[6]),
    exp(coef(coxph_stat_ex_long)[7] + coef(coxph_stat_ex_long)[8])
  ),
  Mixed_Effects = c(
    exp(coef(coxme_stat_ex_long)[1] + coef(coxme_stat_ex_long)[2]),
    exp(coef(coxme_stat_ex_long)[3] + coef(coxme_stat_ex_long)[4]),
    exp(coef(coxme_stat_ex_long)[5] + coef(coxme_stat_ex_long)[6]),
    exp(coef(coxme_stat_ex_long)[7] + coef(coxme_stat_ex_long)[8])
  )
)
```


# Survival analysis

Example survival plot
```{r survival_plot}
full_list_surv <- full_list %>%
  filter(
      CAN_INIT_STAT %in% c(2110, 2120) #, 2130, 2140, 2150, 2160
  ) %>%
  filter(
    unique_date_start <= final_removal_dt
  ) %>%
  mutate(
    can_init_stat_w_ex =
      case_when(
        CAN_INIT_STAT == 2110 &
          rec_exception_init == 0 ~ 1,
        CAN_INIT_STAT == 2110 &
          rec_exception_init == 1 ~ 1.5,
        CAN_INIT_STAT == 2120 &
          rec_exception_init == 0 ~ 2,
        CAN_INIT_STAT == 2120 &
          rec_exception_init == 1 ~ 2.5
      ),
  ) %>%
  group_by(PX_ID) %>%
  summarise(
    survival_time = max(survival_time),
    rec_exception = max(rec_exception),
    rec_exception_init = max(rec_exception_init),
    can_init_stat = first(CANHX_STAT_CD),
    can_init_stat_w_ex = max(can_init_stat_w_ex),
    removal_cause = last(removal_cause),
    death = last(death)
  )

survplot_stat_ex <-
  ggsurvplot(
    fit = survfit(Surv(survival_time, death) ~ can_init_stat_w_ex, data = full_list_surv),
    pval = FALSE,
    pval.coord = c(0,0.25),
    conf.int = FALSE,
    risk.table = TRUE,
    risk.table.col = "strata",
    xlim = c(0, 180),
    xlab = "Days After Listing",
    ylim = c(0.3, 1),
    break.time.by = 30,
    ylab = "Survival Probability",
    legend.labs = c("Status 1 wo exception", "Status 1 w exception", "Status 2 wo exception", "Status 2 w exception"),
    censor = TRUE,
    risk.table.y.text.col = T,
    risk.table.y.text = FALSE,
    tables.height = 0.35
  )

survplot_stat_ex

survplot_ex <-
  ggsurvplot(
    fit = survfit(Surv(survival_time, death) ~ rec_exception_init, data = full_list_surv),
    pval = TRUE,
    pval.coord = c(0,0.73),
    conf.int = FALSE,
    risk.table = TRUE,
    risk.table.col = "strata",
    xlim = c(0, 180),
    xlab = "Days After Listing",
    ylim = c(0.7, 1),
    break.time.by = 30,
    ylab = "Survival Probability",
    legend.labs = c("No exception", "Exception at listing"),
    censor = TRUE,
    risk.table.y.text.col = T,
    risk.table.y.text = FALSE,
    tables.height = 0.3
  )

survplot_ex

# png("survplot_ex.png")
# print(survplot_ex)
```
