---
title: "cox_models"
author: "Daniel Johnson"
date: "2022-08-17"
output:
  pdf_document:
    toc: yes
    toc_depth: '2'
  html_notebook:
    theme: journal
    toc: yes
    toc_depth: 2
    toc_float: yes
---
# Setup

```{r setup, include=FALSE}
library(knitr)
library(tidyverse)
library(coxme)
library(sjPlot)
library(sjlabelled)
library(sjmisc)

knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

# Data sources
```{r data_in}
load("C:/Users/dyjohnson/OneDrive/Documents/Research/SRP/full_list_clean.RData")
```

# Set up data
```{r setup_data}
full_list_cox <- full_list %>%
  filter(unique_date_stop <= final_removal_dt) %>%
  mutate(
    can_stat_active = factor(
      case_when(
        can_stat_active == 2110 ~ "Status 1",
        can_stat_active == 2120 ~ "Status 2",
        can_stat_active == 2130 ~ "Status 3",
        can_stat_active == 2140 ~ "Status 4",
        can_stat_active == 2150 ~ "Status 5",
        can_stat_active == 2160 ~ "Status 6"
      )
    ),
    can_stat_active = relevel(can_stat_active, ref = "Status 6"),
    rec_exception_status = factor(
      case_when(
        can_stat_active == "Status 1" &
          rec_exception == 0 ~ "Status 1 no exception",
        can_stat_active == "Status 1" &
          rec_exception == 1 ~ "Status 1 exception",
        can_stat_active == "Status 2" &
          rec_exception == 0 ~ "Status 2 no exception",
        can_stat_active == "Status 2" &
          rec_exception == 1 ~ "Status 2 exception",
        can_stat_active == "Status 3" &
          rec_exception == 0 ~ "Status 3 no exception",
        can_stat_active == "Status 3" &
          rec_exception == 1 ~ "Status 3 exception",
        can_stat_active == "Status 4" &
          rec_exception == 0 ~ "Status 4 no exception",
        can_stat_active == "Status 4" &
          rec_exception == 1 ~ "Status 4 exception",
        can_stat_active == "Status 5" ~ "Status 5",
        TRUE ~ "Status 6"
      ),
      levels = c(
        "Status 1 no exception",
        "Status 1 exception",
        "Status 2 no exception",
        "Status 2 exception",
        "Status 3 no exception",
        "Status 3 exception",
        "Status 4 no exception",
        "Status 4 exception",
        "Status 5",
        "Status 6"
      )
    ),
    rec_exception_status = relevel(rec_exception_status, ref = "Status 6"),
    lvad = factor(
      case_when(
        CAN_VAD_TY == 2 ~ "LVAD",
        TRUE ~ "No LVAD"
      ),
      levels = c("LVAD",
                 "No LVAD")
    ),
    lvad = relevel(lvad, ref = "No LVAD"),
    except_type = factor(
      case_when(
        CAN_VAD_TY == 2 & rec_exception == 1 ~ "except_vad",
        rec_exception == 1 ~ "except_no_vad",
        TRUE ~ "no_except"
      )
    ),
    except_type = relevel(except_type, ref = "no_except"),
  )
```

# Filter to centers with at least one death
``` {r filter_deaths}
# full_list_cox <- full_list_cox %>% 
#   group_by(CAN_LISTING_CTR_ID) %>%
#   mutate(ctr_deaths = sum(death)) %>%
#   ungroup() %>%
#   filter(ctr_deaths > 0)
```

# All statuses and exceptions
``` {r coxph_stat_ex_long}
coxph_stat_ex_long <- coxph(Surv(t_start, t_stop, death) ~ rec_exception_status, data = full_list_cox)

summary(coxph_stat_ex_long)

plot_model(
  coxph_stat_ex_long,
  show.values = TRUE,
  value.offset = .3,
  axis.labels = c(
    "Status 5",
    "Status 4 exception",
    "Status 4 no exception",
    "Status 3 exception",
    "Status 3 no exception",
    "Status 2 exception",
    "Status 2 no exception",
    "Status 1 exception",
    "Status 1 no exception"
  ),
  title = "Proportional Hazards Model",
  axis.title = "Hazard Ratio"
)

ggsave("coxph_stat_ex_long.png")
```

# All statuses and exceptions and random center effects
``` {r coxme_stat_ex_long}
coxme_stat_ex_long <- coxme(Surv(t_start, t_stop, death) ~ rec_exception_status + (1 | CAN_LISTING_CTR_ID), data = full_list_cox)

summary(coxme_stat_ex_long)

plot_model(
  coxme_stat_ex_long,
  show.values = TRUE,
  value.offset = .3,
  axis.labels = c(
    "Status 5",
    "Status 4 exception",
    "Status 4 no exception",
    "Status 3 exception",
    "Status 3 no exception",
    "Status 2 exception",
    "Status 2 no exception",
    "Status 1 exception",
    "Status 1 no exception"
  ),
  title = "Mixed Effects Model with Center Random Effects",
  axis.title = "Hazard Ratio"
)

ggsave("coxme_stat_ex_long.png")

coxme_stat_ex_long2 <- coxme(Surv(t_start, t_stop, death) ~ can_stat_active + rec_exception + (1 | CAN_LISTING_CTR_ID), data = full_list_cox)

summary(coxme_stat_ex_long2)
exp(confint(coxme_stat_ex_long2))

plot_model(
  coxme_stat_ex_long2,
  show.values = TRUE,
  value.offset = .3,
  axis.labels = c(
    "Exception",
    "Status 5",
    "Status 4",
    "Status 3",
    "Status 2",
    "Status 1"
  ),
  title = "Mixed Effects Model with Center Random Effects",
  axis.title = "Hazard Ratio",
  grid.breaks = c(0.1, 1, 10, 100)
)

ggsave("coxme_stat_ex_long2.png", width = 7, height = 5)
```

# Each status and exceptions and random center effects
```{r coxme_stat_ex}
# Status 1
full_list_cox_stat1 <- full_list_cox %>%
  filter(can_stat_active == "Status 1")

coxme_stat1_ex <- coxme(Surv(t_start, t_stop, death) ~ rec_exception + (1 | CAN_LISTING_CTR_ID), data = full_list_cox_stat1)

summary(coxme_stat1_ex)
exp(confint(coxme_stat1_ex))

# Status 2
full_list_cox_stat2 <- full_list_cox %>%
  filter(can_stat_active == "Status 2")

coxme_stat2_ex <- coxme(Surv(t_start, t_stop, death) ~ rec_exception + (1 | CAN_LISTING_CTR_ID), data = full_list_cox_stat2)

summary(coxme_stat2_ex)
exp(confint(coxme_stat2_ex))

# Status 3
full_list_cox_stat3 <- full_list_cox %>%
  filter(can_stat_active == "Status 3")

coxme_stat3_ex <- coxme(Surv(t_start, t_stop, death) ~ rec_exception + (1 | CAN_LISTING_CTR_ID), data = full_list_cox_stat3)

summary(coxme_stat3_ex)
exp(confint(coxme_stat3_ex))

# Status 4
full_list_cox_stat4 <- full_list_cox %>%
  filter(can_stat_active == "Status 4")

coxme_stat4_ex <- coxme(Surv(t_start, t_stop, death) ~ rec_exception + (1 | CAN_LISTING_CTR_ID), data = full_list_cox_stat4)

summary(coxme_stat4_ex)
exp(confint(coxme_stat4_ex))

# Plot
coxme_stats_ex <- plot_models(
  coxme_stat1_ex,
  coxme_stat2_ex,
  coxme_stat3_ex,
  coxme_stat4_ex,
  axis.labels = "Exception",
  m.labels = c("Status 1", "Status 2", "Status 3", "Status 4"),
  # title = "Mixed Effects Model with Center Random Effects",
  legend.title = "",
  axis.title = "Hazard Ratio of Pre-Transplant Mortality",
  spacing = 1,
  show.values = TRUE,
  show.p = TRUE,
  grid.breaks = c(0.1, 1, 10)
)

coxme_stats_ex$layers[[4]]$aes_params$hjust <- 0.4

coxme_stats_ex 

ggsave("coxme_stats_ex2.png", width = 7, height = 5)
```
# All statuses and exceptions, LVAD interaction, and random center effects
``` {r coxme_lvad}
coxme_lvad <- coxme(Surv(t_start, t_stop, death) ~ can_stat_active + rec_exception*lvad + (1 | CAN_LISTING_CTR_ID), data = full_list_cox)

summary(coxme_lvad)

plot_model(
  coxme_lvad,
  show.values = TRUE,
  value.offset = .3,
  axis.labels = c(
    "Exception * LVAD",
    "LVAD",
    "Exception",
    "Status 5",
    "Status 4",
    "Status 3",
    "Status 2",
    "Status 1"
  ),
  title = "Mixed Effects Model with Center Random Effects and LVAD Interaction",
  axis.title = "Hazard Ratio"
)

ggsave("coxme_lvad.png", width = 7, height = 5)

coxme_lvad2 <- coxme(Surv(t_start, t_stop, death) ~ can_stat_active + except_type + (1 | CAN_LISTING_CTR_ID), data = full_list_cox)

summary(coxme_lvad2)
exp(confint(coxme_lvad2))

plot_model(
  coxme_lvad2,
  show.values = TRUE,
  value.offset = .3,
  axis.labels = c(
    "Exception with LVAD",
    "Exception without LVAD",
    "Status 5",
    "Status 4",
    "Status 3",
    "Status 2",
    "Status 1"
  ),
  title = "Mixed Effects Model with Center Random Effects and LVAD Interaction",
  axis.title = "Hazard Ratio"
)

ggsave("coxme_lvad2.png", width = 7, height = 5)

coxme_lvad3 <- coxme(Surv(t_start, t_stop, death) ~ can_stat_active + except_type + (1 | CAN_LISTING_CTR_ID), data = full_list_cox %>% mutate(except_type = relevel(except_type, ref = "except_no_vad")))

summary(coxme_lvad3)
```