---
title: "kaplan_meier_curve"
author: "Daniel Johnson"
date: "2022-08-11"
output:
  pdf_document:
    toc: yes
    toc_depth: '2'
  html_notebook:
    theme: journal
    toc: yes
    toc_depth: 2
    toc_float: yes
---
# Setup

```{r setup, include=FALSE}
library(knitr)
library(tidyverse)
library(survminer)

knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

# Data sources
```{r data_in}
load("C:/Users/dyjohnson/OneDrive/Documents/Research/SRP/full_list_clean.RData")
```

# Survival analysis
```{r survival_plot}
full_list_surv <- full_list %>%
  filter(
      CAN_INIT_STAT %in% c(2110, 2120) #, 2130, 2140, 2150, 2160
  ) %>%
  filter(
    unique_date_stop <= final_removal_dt
  ) %>%
  mutate(
    can_init_stat_w_ex =
      case_when(
        CAN_INIT_STAT == 2110 &
          rec_exception_init == 0 ~ 1,
        CAN_INIT_STAT == 2110 &
          rec_exception_init == 1 ~ 1.5,
        CAN_INIT_STAT == 2120 &
          rec_exception_init == 0 ~ 2,
        CAN_INIT_STAT == 2120 &
          rec_exception_init == 1 ~ 2.5
      ),
  ) %>%
  group_by(PX_ID) %>%
  summarise(
    survival_time = max(survival_time),
    rec_exception = max(rec_exception),
    rec_exception_init = max(rec_exception_init),
    can_init_stat = first(CANHX_STAT_CD),
    can_init_stat_w_ex = max(can_init_stat_w_ex),
    removal_cause = last(removal_cause),
    death = last(death)
  )

survplot_stat_ex <-
  ggsurvplot(
    fit = survfit(Surv(survival_time, death) ~ can_init_stat_w_ex, data = full_list_surv),
    pval = FALSE,
    pval.coord = c(0,0.25),
    conf.int = FALSE,
    risk.table = TRUE,
    risk.table.col = "strata",
    xlim = c(0, 180),
    xlab = "Days After Listing",
    ylim = c(0.3, 1),
    break.time.by = 30,
    ylab = "Survival Probability",
    legend.labs = c("Status 1 wo exception", "Status 1 w exception", "Status 2 wo exception", "Status 2 w exception"),
    censor = TRUE,
    risk.table.y.text.col = T,
    risk.table.y.text = FALSE,
    tables.height = 0.35
  )

survplot_stat_ex

survplot_ex <-
  ggsurvplot(
    fit = survfit(Surv(survival_time, death) ~ rec_exception_init, data = full_list_surv),
    pval = TRUE,
    pval.coord = c(0,0.73),
    conf.int = FALSE,
    risk.table = TRUE,
    risk.table.col = "strata",
    xlim = c(0, 180),
    xlab = "Days After Listing",
    ylim = c(0.7, 1),
    break.time.by = 30,
    ylab = "Survival Probability",
    legend.labs = c("No exception at listing", "Exception at listing"),
    censor = TRUE,
    risk.table.y.text.col = T,
    risk.table.y.text = FALSE,
    tables.height = 0.3
  )

survplot_ex

# png("survplot_ex.png")
# print(survplot_ex)
```
